author: Saiho Yeung
title: SAIHO Clothing Manufacturer
email: yshshihao@163.com 
description: >-
  SAIHO located in Foshan, Guandong is a newly established clothing enterprise,
  producing custom garments for start-up, small to medium sized clothing brands
  at the lowest MOQ, from 50pcs. The designers, quality control personnel and managers 
  in the company have more than 30 years of work experience. Pattern making, sample
  making and other services will be provided.
baseurl: "/saihogarment"
url: ""

logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

include: ['_pages']
permalink: /:title/

address: Foshan, Guangdong, China
phoneNumber: +86 1368 7417 194